parameters:
    locale: 'en'
    faker_locale: 'en_GB'
    app_locales: ['fr', '%locale%']
    app_locales_regex: 'fr|%locale%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # Aliases to TimeContinuum
    app.earth:
        class: Innmind\TimeContinuum\TimeContinuum\Earth
    app.format:
        class: Innmind\TimeContinuum\Format\ISO8601

    # Creating a service with TimeContinuum
    App\Service\GlobalClock:
        arguments:
            $clock: '@app.earth'
            $format: '@app.format'

    App\Listener\AuthenticationListener:
        tags: ['kernel.event_listener']
